site_name: DOC ALT2030
dev_addr: '0.0.0.0:8080'
plugins:
    - render_swagger
nav:
    - Home: index.md
    - Methodologie :
        - Nomenclature : methodo/nomenclature.md
        - Equipements brutes : methodo/equipement_brute.md
        - Utilisation : methodo/utilisation.md
        - Autres regles : methodo/regles_additionnels.md
        - Infrastructure : methodo/infra.md
        - Infrastructure Cloud : methodo/infra_cloud.md
        - Profil : methodo/profil.md
        - Departement : methodo/departement.md
        - Entreprise : methodo/entreprise.md
        - Services : methodo/services.md
        - Maturité : methodo/maturite.md
    - Utilisateur :
        - TUTO : utilisateur/tuto.md
    - Technique :
        - Flux de données : technique/flux_donnees.md
        - Technologies : technique/technologies.md
        - CI/CD : technique/CI-CD.md
        - API IMPACT : technique/api_impact.md
        - Securité : technique/securite.md
theme: readthedocs