name: API_IMPACT CI/CD

on :
  push : 
    branches : [ master ]

jobs :
  build-images :
    runs-on : ubuntu-latest
    
    steps:
         # Log into github registry    
         - name: Log into registry
           run: echo ${{ secrets.ACCESS_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin  
         # Check out the repo    
         - name: Checkout
           uses: actions/checkout@v2
         # Build the images    
         - name: Build the docker-compose stack  
           run: docker-compose build
         - name : tag 
           run: docker tag ghcr.io/omconseil/alt2030_doc:latest ghcr.io/omconseil/alt2030_doc:${{ GITHUB_SHA }}
         # Push images
         - name: Push images 
           run: docker push -a ghcr.io/omconseil/alt2030_doc
